# Generated by Django 3.2.8 on 2021-10-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='C:\\Users\\Clinton Cunha\\Desktop\\Desktop\\Weekly Activities\\Week17\\Django\\mysite\\myapp')),
                ('file', models.FileField(upload_to='C:\\Users\\Clinton Cunha\\Desktop\\Desktop\\Weekly Activities\\Week17\\Django\\mysite\\myapp')),
            ],
        ),
    ]
