# Generated by Django 3.2.8 on 2021-10-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='C:\\Users\\Clinton Cunha\\Desktop\\Desktop\\Weekly Activities\\Week17\\Django\\mysite\\myapp')),
            ],
        ),
    ]
